service:
  name: order-service
  env: local
http:
  addr: :8003
  timeout: 5s
grpc:
  addr: :9003
  timeout: 5s
mysql:
  dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub_order?parseTime=true&loc=Local&charset=utf8mb4
sharding:
  enabled: false
  database_prefix: tickethub_order
  table_prefix: orders
  database_count: 2
  table_count: 2
  databases:
    tickethub_order_0:
      dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub_order_0?parseTime=true&loc=Local&charset=utf8mb4
    tickethub_order_1:
      dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub_order_1?parseTime=true&loc=Local&charset=utf8mb4
    tickethub_order_2:
      dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub_order_2?parseTime=true&loc=Local&charset=utf8mb4
redis:
  addr: 127.0.0.1:6379
  key_prefix: tickethub:order
workers:
  disabled: []
  poll_interval: 1s
  create_batch_size: 32
  cancel_batch_size: 32
  cancel_delay: 15m
  delay_visibility_timeout: 2m
  fail_before_ack_count: 0
kafka:
  brokers: [127.0.0.1:9094]
  client_id: order-service
  group_id: order-service
  topics:
    create_order: ticket_hub.create_order
grpc_upstreams:
  program-service: 127.0.0.1:9002
  migrate-service: 127.0.0.1:9008
observability:
  metrics_addr: :19003
  trace_otlp: http://127.0.0.1:4318
  log_level: info
