// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: base/v1/base.proto

package basev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BaseDataService_ListAreas_FullMethodName       = "/tickethub.base.v1.BaseDataService/ListAreas"
	BaseDataService_ListChannelData_FullMethodName = "/tickethub.base.v1.BaseDataService/ListChannelData"
)

// BaseDataServiceClient is the client API for BaseDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseDataServiceClient interface {
	ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasReply, error)
	ListChannelData(ctx context.Context, in *ListChannelDataRequest, opts ...grpc.CallOption) (*ListChannelDataReply, error)
}

type baseDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseDataServiceClient(cc grpc.ClientConnInterface) BaseDataServiceClient {
	return &baseDataServiceClient{cc}
}

func (c *baseDataServiceClient) ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasReply, error) {
	out := new(ListAreasReply)
	err := c.cc.Invoke(ctx, BaseDataService_ListAreas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseDataServiceClient) ListChannelData(ctx context.Context, in *ListChannelDataRequest, opts ...grpc.CallOption) (*ListChannelDataReply, error) {
	out := new(ListChannelDataReply)
	err := c.cc.Invoke(ctx, BaseDataService_ListChannelData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseDataServiceServer is the server API for BaseDataService service.
// All implementations must embed UnimplementedBaseDataServiceServer
// for forward compatibility
type BaseDataServiceServer interface {
	ListAreas(context.Context, *ListAreasRequest) (*ListAreasReply, error)
	ListChannelData(context.Context, *ListChannelDataRequest) (*ListChannelDataReply, error)
	mustEmbedUnimplementedBaseDataServiceServer()
}

// UnimplementedBaseDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBaseDataServiceServer struct {
}

func (UnimplementedBaseDataServiceServer) ListAreas(context.Context, *ListAreasRequest) (*ListAreasReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAreas not implemented")
}
func (UnimplementedBaseDataServiceServer) ListChannelData(context.Context, *ListChannelDataRequest) (*ListChannelDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannelData not implemented")
}
func (UnimplementedBaseDataServiceServer) mustEmbedUnimplementedBaseDataServiceServer() {}

// UnsafeBaseDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseDataServiceServer will
// result in compilation errors.
type UnsafeBaseDataServiceServer interface {
	mustEmbedUnimplementedBaseDataServiceServer()
}

func RegisterBaseDataServiceServer(s grpc.ServiceRegistrar, srv BaseDataServiceServer) {
	s.RegisterService(&BaseDataService_ServiceDesc, srv)
}

func _BaseDataService_ListAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseDataServiceServer).ListAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseDataService_ListAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseDataServiceServer).ListAreas(ctx, req.(*ListAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseDataService_ListChannelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseDataServiceServer).ListChannelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseDataService_ListChannelData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseDataServiceServer).ListChannelData(ctx, req.(*ListChannelDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseDataService_ServiceDesc is the grpc.ServiceDesc for BaseDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickethub.base.v1.BaseDataService",
	HandlerType: (*BaseDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAreas",
			Handler:    _BaseDataService_ListAreas_Handler,
		},
		{
			MethodName: "ListChannelData",
			Handler:    _BaseDataService_ListChannelData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/v1/base.proto",
}
