// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: migrate/v1/migrate.proto

package migratev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceShard  string `protobuf:"bytes,1,opt,name=source_shard,json=sourceShard,proto3" json:"source_shard,omitempty"`
	TargetShard  string `protobuf:"bytes,2,opt,name=target_shard,json=targetShard,proto3" json:"target_shard,omitempty"`
	BatchSize    int32  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	VirtualShard int32  `protobuf:"varint,4,opt,name=virtual_shard,json=virtualShard,proto3" json:"virtual_shard,omitempty"`
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetSourceShard() string {
	if x != nil {
		return x.SourceShard
	}
	return ""
}

func (x *CreateTaskRequest) GetTargetShard() string {
	if x != nil {
		return x.TargetShard
	}
	return ""
}

func (x *CreateTaskRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *CreateTaskRequest) GetVirtualShard() int32 {
	if x != nil {
		return x.VirtualShard
	}
	return 0
}

type CreateTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId       int64  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VirtualShard int32  `protobuf:"varint,2,opt,name=virtual_shard,json=virtualShard,proto3" json:"virtual_shard,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateTaskReply) Reset() {
	*x = CreateTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReply) ProtoMessage() {}

func (x *CreateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReply.ProtoReflect.Descriptor instead.
func (*CreateTaskReply) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskReply) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateTaskReply) GetVirtualShard() int32 {
	if x != nil {
		return x.VirtualShard
	}
	return 0
}

func (x *CreateTaskReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResumeTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ResumeTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId int64  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResumeTaskReply) Reset() {
	*x = ResumeTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskReply) ProtoMessage() {}

func (x *ResumeTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskReply.ProtoReflect.Descriptor instead.
func (*ResumeTaskReply) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeTaskReply) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ResumeTaskReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListShardMappingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListShardMappingsRequest) Reset() {
	*x = ListShardMappingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShardMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardMappingsRequest) ProtoMessage() {}

func (x *ListShardMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardMappingsRequest.ProtoReflect.Descriptor instead.
func (*ListShardMappingsRequest) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{4}
}

type ListShardMappingsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mappings []*ShardMapping `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
}

func (x *ListShardMappingsReply) Reset() {
	*x = ListShardMappingsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListShardMappingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardMappingsReply) ProtoMessage() {}

func (x *ListShardMappingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardMappingsReply.ProtoReflect.Descriptor instead.
func (*ListShardMappingsReply) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{5}
}

func (x *ListShardMappingsReply) GetMappings() []*ShardMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type ShardMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualShard  int32  `protobuf:"varint,1,opt,name=virtual_shard,json=virtualShard,proto3" json:"virtual_shard,omitempty"`
	PhysicalDb    string `protobuf:"bytes,2,opt,name=physical_db,json=physicalDb,proto3" json:"physical_db,omitempty"`
	PhysicalTable string `protobuf:"bytes,3,opt,name=physical_table,json=physicalTable,proto3" json:"physical_table,omitempty"`
	ShadowDb      string `protobuf:"bytes,4,opt,name=shadow_db,json=shadowDb,proto3" json:"shadow_db,omitempty"`
	ShadowTable   string `protobuf:"bytes,5,opt,name=shadow_table,json=shadowTable,proto3" json:"shadow_table,omitempty"`
	WriteMode     string `protobuf:"bytes,6,opt,name=write_mode,json=writeMode,proto3" json:"write_mode,omitempty"`
	Version       int64  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ShardMapping) Reset() {
	*x = ShardMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_v1_migrate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMapping) ProtoMessage() {}

func (x *ShardMapping) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_v1_migrate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMapping.ProtoReflect.Descriptor instead.
func (*ShardMapping) Descriptor() ([]byte, []int) {
	return file_migrate_v1_migrate_proto_rawDescGZIP(), []int{6}
}

func (x *ShardMapping) GetVirtualShard() int32 {
	if x != nil {
		return x.VirtualShard
	}
	return 0
}

func (x *ShardMapping) GetPhysicalDb() string {
	if x != nil {
		return x.PhysicalDb
	}
	return ""
}

func (x *ShardMapping) GetPhysicalTable() string {
	if x != nil {
		return x.PhysicalTable
	}
	return ""
}

func (x *ShardMapping) GetShadowDb() string {
	if x != nil {
		return x.ShadowDb
	}
	return ""
}

func (x *ShardMapping) GetShadowTable() string {
	if x != nil {
		return x.ShadowTable
	}
	return ""
}

func (x *ShardMapping) GetWriteMode() string {
	if x != nil {
		return x.WriteMode
	}
	return ""
}

func (x *ShardMapping) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_migrate_v1_migrate_proto protoreflect.FileDescriptor

var file_migrate_v1_migrate_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x9d, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76,
	0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x22, 0x67, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6d,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3e, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x73, 0x22, 0xf4, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x53, 0x68, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x5f, 0x64, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x62, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x68, 0x79, 0x73,
	0x69, 0x63, 0x61, 0x6c, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x5f, 0x64, 0x62, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x44, 0x62, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0xbf, 0x02, 0x0a, 0x0e, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x27, 0x2e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a, 0x0a, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x27, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x71, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x2e, 0x2e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2a, 0x5a, 0x28, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_migrate_v1_migrate_proto_rawDescOnce sync.Once
	file_migrate_v1_migrate_proto_rawDescData = file_migrate_v1_migrate_proto_rawDesc
)

func file_migrate_v1_migrate_proto_rawDescGZIP() []byte {
	file_migrate_v1_migrate_proto_rawDescOnce.Do(func() {
		file_migrate_v1_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_migrate_v1_migrate_proto_rawDescData)
	})
	return file_migrate_v1_migrate_proto_rawDescData
}

var file_migrate_v1_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_migrate_v1_migrate_proto_goTypes = []interface{}{
	(*CreateTaskRequest)(nil),        // 0: tickethub.migrate.v1.CreateTaskRequest
	(*CreateTaskReply)(nil),          // 1: tickethub.migrate.v1.CreateTaskReply
	(*ResumeTaskRequest)(nil),        // 2: tickethub.migrate.v1.ResumeTaskRequest
	(*ResumeTaskReply)(nil),          // 3: tickethub.migrate.v1.ResumeTaskReply
	(*ListShardMappingsRequest)(nil), // 4: tickethub.migrate.v1.ListShardMappingsRequest
	(*ListShardMappingsReply)(nil),   // 5: tickethub.migrate.v1.ListShardMappingsReply
	(*ShardMapping)(nil),             // 6: tickethub.migrate.v1.ShardMapping
}
var file_migrate_v1_migrate_proto_depIdxs = []int32{
	6, // 0: tickethub.migrate.v1.ListShardMappingsReply.mappings:type_name -> tickethub.migrate.v1.ShardMapping
	0, // 1: tickethub.migrate.v1.MigrateService.CreateTask:input_type -> tickethub.migrate.v1.CreateTaskRequest
	2, // 2: tickethub.migrate.v1.MigrateService.ResumeTask:input_type -> tickethub.migrate.v1.ResumeTaskRequest
	4, // 3: tickethub.migrate.v1.MigrateService.ListShardMappings:input_type -> tickethub.migrate.v1.ListShardMappingsRequest
	1, // 4: tickethub.migrate.v1.MigrateService.CreateTask:output_type -> tickethub.migrate.v1.CreateTaskReply
	3, // 5: tickethub.migrate.v1.MigrateService.ResumeTask:output_type -> tickethub.migrate.v1.ResumeTaskReply
	5, // 6: tickethub.migrate.v1.MigrateService.ListShardMappings:output_type -> tickethub.migrate.v1.ListShardMappingsReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_migrate_v1_migrate_proto_init() }
func file_migrate_v1_migrate_proto_init() {
	if File_migrate_v1_migrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_migrate_v1_migrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResumeTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShardMappingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListShardMappingsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_v1_migrate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_migrate_v1_migrate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migrate_v1_migrate_proto_goTypes,
		DependencyIndexes: file_migrate_v1_migrate_proto_depIdxs,
		MessageInfos:      file_migrate_v1_migrate_proto_msgTypes,
	}.Build()
	File_migrate_v1_migrate_proto = out.File
	file_migrate_v1_migrate_proto_rawDesc = nil
	file_migrate_v1_migrate_proto_goTypes = nil
	file_migrate_v1_migrate_proto_depIdxs = nil
}
