// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: migrate/v1/migrate.proto

package migratev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MigrateService_CreateTask_FullMethodName        = "/tickethub.migrate.v1.MigrateService/CreateTask"
	MigrateService_ResumeTask_FullMethodName        = "/tickethub.migrate.v1.MigrateService/ResumeTask"
	MigrateService_ListShardMappings_FullMethodName = "/tickethub.migrate.v1.MigrateService/ListShardMappings"
)

// MigrateServiceClient is the client API for MigrateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrateServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error)
	ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*ResumeTaskReply, error)
	ListShardMappings(ctx context.Context, in *ListShardMappingsRequest, opts ...grpc.CallOption) (*ListShardMappingsReply, error)
}

type migrateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrateServiceClient(cc grpc.ClientConnInterface) MigrateServiceClient {
	return &migrateServiceClient{cc}
}

func (c *migrateServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error) {
	out := new(CreateTaskReply)
	err := c.cc.Invoke(ctx, MigrateService_CreateTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrateServiceClient) ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*ResumeTaskReply, error) {
	out := new(ResumeTaskReply)
	err := c.cc.Invoke(ctx, MigrateService_ResumeTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migrateServiceClient) ListShardMappings(ctx context.Context, in *ListShardMappingsRequest, opts ...grpc.CallOption) (*ListShardMappingsReply, error) {
	out := new(ListShardMappingsReply)
	err := c.cc.Invoke(ctx, MigrateService_ListShardMappings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrateServiceServer is the server API for MigrateService service.
// All implementations must embed UnimplementedMigrateServiceServer
// for forward compatibility
type MigrateServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error)
	ResumeTask(context.Context, *ResumeTaskRequest) (*ResumeTaskReply, error)
	ListShardMappings(context.Context, *ListShardMappingsRequest) (*ListShardMappingsReply, error)
	mustEmbedUnimplementedMigrateServiceServer()
}

// UnimplementedMigrateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMigrateServiceServer struct {
}

func (UnimplementedMigrateServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedMigrateServiceServer) ResumeTask(context.Context, *ResumeTaskRequest) (*ResumeTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeTask not implemented")
}
func (UnimplementedMigrateServiceServer) ListShardMappings(context.Context, *ListShardMappingsRequest) (*ListShardMappingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShardMappings not implemented")
}
func (UnimplementedMigrateServiceServer) mustEmbedUnimplementedMigrateServiceServer() {}

// UnsafeMigrateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrateServiceServer will
// result in compilation errors.
type UnsafeMigrateServiceServer interface {
	mustEmbedUnimplementedMigrateServiceServer()
}

func RegisterMigrateServiceServer(s grpc.ServiceRegistrar, srv MigrateServiceServer) {
	s.RegisterService(&MigrateService_ServiceDesc, srv)
}

func _MigrateService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrateServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrateService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrateServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrateService_ResumeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrateServiceServer).ResumeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrateService_ResumeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrateServiceServer).ResumeTask(ctx, req.(*ResumeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MigrateService_ListShardMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrateServiceServer).ListShardMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MigrateService_ListShardMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrateServiceServer).ListShardMappings(ctx, req.(*ListShardMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MigrateService_ServiceDesc is the grpc.ServiceDesc for MigrateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MigrateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickethub.migrate.v1.MigrateService",
	HandlerType: (*MigrateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _MigrateService_CreateTask_Handler,
		},
		{
			MethodName: "ResumeTask",
			Handler:    _MigrateService_ResumeTask_Handler,
		},
		{
			MethodName: "ListShardMappings",
			Handler:    _MigrateService_ListShardMappings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migrate/v1/migrate.proto",
}
