// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: program/v1/program.proto

package programv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProgramService_SearchProgram_FullMethodName       = "/tickethub.program.v1.ProgramService/SearchProgram"
	ProgramService_GetProgramDetail_FullMethodName    = "/tickethub.program.v1.ProgramService/GetProgramDetail"
	ProgramService_CreateOrder_FullMethodName         = "/tickethub.program.v1.ProgramService/CreateOrder"
	ProgramService_ConfirmSeatsSold_FullMethodName    = "/tickethub.program.v1.ProgramService/ConfirmSeatsSold"
	ProgramService_ReleaseSeats_FullMethodName        = "/tickethub.program.v1.ProgramService/ReleaseSeats"
	ProgramService_RollbackCreateOrder_FullMethodName = "/tickethub.program.v1.ProgramService/RollbackCreateOrder"
	ProgramService_ReserveCreateOrder_FullMethodName  = "/tickethub.program.v1.ProgramService/ReserveCreateOrder"
	ProgramService_ReconcileInventory_FullMethodName  = "/tickethub.program.v1.ProgramService/ReconcileInventory"
)

// ProgramServiceClient is the client API for ProgramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramServiceClient interface {
	SearchProgram(ctx context.Context, in *SearchProgramRequest, opts ...grpc.CallOption) (*SearchProgramReply, error)
	GetProgramDetail(ctx context.Context, in *GetProgramDetailRequest, opts ...grpc.CallOption) (*ProgramDetail, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	ConfirmSeatsSold(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error)
	ReleaseSeats(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error)
	RollbackCreateOrder(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error)
	ReserveCreateOrder(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error)
	ReconcileInventory(ctx context.Context, in *ReconcileInventoryRequest, opts ...grpc.CallOption) (*ReconcileInventoryReply, error)
}

type programServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramServiceClient(cc grpc.ClientConnInterface) ProgramServiceClient {
	return &programServiceClient{cc}
}

func (c *programServiceClient) SearchProgram(ctx context.Context, in *SearchProgramRequest, opts ...grpc.CallOption) (*SearchProgramReply, error) {
	out := new(SearchProgramReply)
	err := c.cc.Invoke(ctx, ProgramService_SearchProgram_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) GetProgramDetail(ctx context.Context, in *GetProgramDetailRequest, opts ...grpc.CallOption) (*ProgramDetail, error) {
	out := new(ProgramDetail)
	err := c.cc.Invoke(ctx, ProgramService_GetProgramDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, ProgramService_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) ConfirmSeatsSold(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error) {
	out := new(SeatOperationReply)
	err := c.cc.Invoke(ctx, ProgramService_ConfirmSeatsSold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) ReleaseSeats(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error) {
	out := new(SeatOperationReply)
	err := c.cc.Invoke(ctx, ProgramService_ReleaseSeats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) RollbackCreateOrder(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error) {
	out := new(SeatOperationReply)
	err := c.cc.Invoke(ctx, ProgramService_RollbackCreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) ReserveCreateOrder(ctx context.Context, in *SeatOperationRequest, opts ...grpc.CallOption) (*SeatOperationReply, error) {
	out := new(SeatOperationReply)
	err := c.cc.Invoke(ctx, ProgramService_ReserveCreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programServiceClient) ReconcileInventory(ctx context.Context, in *ReconcileInventoryRequest, opts ...grpc.CallOption) (*ReconcileInventoryReply, error) {
	out := new(ReconcileInventoryReply)
	err := c.cc.Invoke(ctx, ProgramService_ReconcileInventory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramServiceServer is the server API for ProgramService service.
// All implementations must embed UnimplementedProgramServiceServer
// for forward compatibility
type ProgramServiceServer interface {
	SearchProgram(context.Context, *SearchProgramRequest) (*SearchProgramReply, error)
	GetProgramDetail(context.Context, *GetProgramDetailRequest) (*ProgramDetail, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	ConfirmSeatsSold(context.Context, *SeatOperationRequest) (*SeatOperationReply, error)
	ReleaseSeats(context.Context, *SeatOperationRequest) (*SeatOperationReply, error)
	RollbackCreateOrder(context.Context, *SeatOperationRequest) (*SeatOperationReply, error)
	ReserveCreateOrder(context.Context, *SeatOperationRequest) (*SeatOperationReply, error)
	ReconcileInventory(context.Context, *ReconcileInventoryRequest) (*ReconcileInventoryReply, error)
	mustEmbedUnimplementedProgramServiceServer()
}

// UnimplementedProgramServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProgramServiceServer struct {
}

func (UnimplementedProgramServiceServer) SearchProgram(context.Context, *SearchProgramRequest) (*SearchProgramReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProgram not implemented")
}
func (UnimplementedProgramServiceServer) GetProgramDetail(context.Context, *GetProgramDetailRequest) (*ProgramDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgramDetail not implemented")
}
func (UnimplementedProgramServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedProgramServiceServer) ConfirmSeatsSold(context.Context, *SeatOperationRequest) (*SeatOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmSeatsSold not implemented")
}
func (UnimplementedProgramServiceServer) ReleaseSeats(context.Context, *SeatOperationRequest) (*SeatOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseSeats not implemented")
}
func (UnimplementedProgramServiceServer) RollbackCreateOrder(context.Context, *SeatOperationRequest) (*SeatOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackCreateOrder not implemented")
}
func (UnimplementedProgramServiceServer) ReserveCreateOrder(context.Context, *SeatOperationRequest) (*SeatOperationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveCreateOrder not implemented")
}
func (UnimplementedProgramServiceServer) ReconcileInventory(context.Context, *ReconcileInventoryRequest) (*ReconcileInventoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconcileInventory not implemented")
}
func (UnimplementedProgramServiceServer) mustEmbedUnimplementedProgramServiceServer() {}

// UnsafeProgramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramServiceServer will
// result in compilation errors.
type UnsafeProgramServiceServer interface {
	mustEmbedUnimplementedProgramServiceServer()
}

func RegisterProgramServiceServer(s grpc.ServiceRegistrar, srv ProgramServiceServer) {
	s.RegisterService(&ProgramService_ServiceDesc, srv)
}

func _ProgramService_SearchProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).SearchProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_SearchProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).SearchProgram(ctx, req.(*SearchProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_GetProgramDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).GetProgramDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_GetProgramDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).GetProgramDetail(ctx, req.(*GetProgramDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_ConfirmSeatsSold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ConfirmSeatsSold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ConfirmSeatsSold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ConfirmSeatsSold(ctx, req.(*SeatOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_ReleaseSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ReleaseSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ReleaseSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ReleaseSeats(ctx, req.(*SeatOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_RollbackCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).RollbackCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_RollbackCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).RollbackCreateOrder(ctx, req.(*SeatOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_ReserveCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ReserveCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ReserveCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ReserveCreateOrder(ctx, req.(*SeatOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramService_ReconcileInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServiceServer).ReconcileInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramService_ReconcileInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServiceServer).ReconcileInventory(ctx, req.(*ReconcileInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgramService_ServiceDesc is the grpc.ServiceDesc for ProgramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickethub.program.v1.ProgramService",
	HandlerType: (*ProgramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProgram",
			Handler:    _ProgramService_SearchProgram_Handler,
		},
		{
			MethodName: "GetProgramDetail",
			Handler:    _ProgramService_GetProgramDetail_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _ProgramService_CreateOrder_Handler,
		},
		{
			MethodName: "ConfirmSeatsSold",
			Handler:    _ProgramService_ConfirmSeatsSold_Handler,
		},
		{
			MethodName: "ReleaseSeats",
			Handler:    _ProgramService_ReleaseSeats_Handler,
		},
		{
			MethodName: "RollbackCreateOrder",
			Handler:    _ProgramService_RollbackCreateOrder_Handler,
		},
		{
			MethodName: "ReserveCreateOrder",
			Handler:    _ProgramService_ReserveCreateOrder_Handler,
		},
		{
			MethodName: "ReconcileInventory",
			Handler:    _ProgramService_ReconcileInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "program/v1/program.proto",
}
