// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: customize/v1/customize.proto

package customizev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CustomizeService_RecordMessage_FullMethodName = "/tickethub.customize.v1.CustomizeService/RecordMessage"
)

// CustomizeServiceClient is the client API for CustomizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomizeServiceClient interface {
	RecordMessage(ctx context.Context, in *RecordMessageRequest, opts ...grpc.CallOption) (*RecordMessageReply, error)
}

type customizeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomizeServiceClient(cc grpc.ClientConnInterface) CustomizeServiceClient {
	return &customizeServiceClient{cc}
}

func (c *customizeServiceClient) RecordMessage(ctx context.Context, in *RecordMessageRequest, opts ...grpc.CallOption) (*RecordMessageReply, error) {
	out := new(RecordMessageReply)
	err := c.cc.Invoke(ctx, CustomizeService_RecordMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomizeServiceServer is the server API for CustomizeService service.
// All implementations must embed UnimplementedCustomizeServiceServer
// for forward compatibility
type CustomizeServiceServer interface {
	RecordMessage(context.Context, *RecordMessageRequest) (*RecordMessageReply, error)
	mustEmbedUnimplementedCustomizeServiceServer()
}

// UnimplementedCustomizeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomizeServiceServer struct {
}

func (UnimplementedCustomizeServiceServer) RecordMessage(context.Context, *RecordMessageRequest) (*RecordMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordMessage not implemented")
}
func (UnimplementedCustomizeServiceServer) mustEmbedUnimplementedCustomizeServiceServer() {}

// UnsafeCustomizeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomizeServiceServer will
// result in compilation errors.
type UnsafeCustomizeServiceServer interface {
	mustEmbedUnimplementedCustomizeServiceServer()
}

func RegisterCustomizeServiceServer(s grpc.ServiceRegistrar, srv CustomizeServiceServer) {
	s.RegisterService(&CustomizeService_ServiceDesc, srv)
}

func _CustomizeService_RecordMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomizeServiceServer).RecordMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomizeService_RecordMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomizeServiceServer).RecordMessage(ctx, req.(*RecordMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomizeService_ServiceDesc is the grpc.ServiceDesc for CustomizeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomizeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tickethub.customize.v1.CustomizeService",
	HandlerType: (*CustomizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordMessage",
			Handler:    _CustomizeService_RecordMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customize/v1/customize.proto",
}
