global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "tickethub-apisix"
    metrics_path: /apisix/prometheus/metrics
    static_configs:
      - targets:
          - "tickethub-apisix:9091"

  - job_name: "tickethub-services"
    static_configs:
      - targets:
          - "gateway-bff:8080"
          - "user-service:8001"
          - "program-service:8002"
          - "order-service:8003"
          - "pay-service:8004"
          - "base-data-service:8005"
          - "customize-service:8006"
          - "admin-service:8007"
          - "migrate-service:8008"
