// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: pay/v1/pay.proto

package payv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonPayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumber int64  `protobuf:"varint,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	AmountCent  int64  `protobuf:"varint,2,opt,name=amount_cent,json=amountCent,proto3" json:"amount_cent,omitempty"`
	Channel     string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId      int64  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CommonPayRequest) Reset() {
	*x = CommonPayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonPayRequest) ProtoMessage() {}

func (x *CommonPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonPayRequest.ProtoReflect.Descriptor instead.
func (*CommonPayRequest) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{0}
}

func (x *CommonPayRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *CommonPayRequest) GetAmountCent() int64 {
	if x != nil {
		return x.AmountCent
	}
	return 0
}

func (x *CommonPayRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CommonPayRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CommonPayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayUrl string `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
}

func (x *CommonPayReply) Reset() {
	*x = CommonPayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonPayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonPayReply) ProtoMessage() {}

func (x *CommonPayReply) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonPayReply.ProtoReflect.Descriptor instead.
func (*CommonPayReply) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{1}
}

func (x *CommonPayReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

type TradeCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumber int64  `protobuf:"varint,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Channel     string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId      int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *TradeCheckRequest) Reset() {
	*x = TradeCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCheckRequest) ProtoMessage() {}

func (x *TradeCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCheckRequest.ProtoReflect.Descriptor instead.
func (*TradeCheckRequest) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{2}
}

func (x *TradeCheckRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *TradeCheckRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *TradeCheckRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TradeCheckReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paid bool `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
}

func (x *TradeCheckReply) Reset() {
	*x = TradeCheckReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeCheckReply) ProtoMessage() {}

func (x *TradeCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeCheckReply.ProtoReflect.Descriptor instead.
func (*TradeCheckReply) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{3}
}

func (x *TradeCheckReply) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

type RefundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNumber int64  `protobuf:"varint,1,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	AmountCent  int64  `protobuf:"varint,2,opt,name=amount_cent,json=amountCent,proto3" json:"amount_cent,omitempty"`
	Reason      string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{4}
}

func (x *RefundRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *RefundRequest) GetAmountCent() int64 {
	if x != nil {
		return x.AmountCent
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RefundReply) Reset() {
	*x = RefundReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_v1_pay_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundReply) ProtoMessage() {}

func (x *RefundReply) ProtoReflect() protoreflect.Message {
	mi := &file_pay_v1_pay_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundReply.ProtoReflect.Descriptor instead.
func (*RefundReply) Descriptor() ([]byte, []int) {
	return file_pay_v1_pay_proto_rawDescGZIP(), []int{5}
}

func (x *RefundReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pay_v1_pay_proto protoreflect.FileDescriptor

var file_pay_v1_pay_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x22, 0x89, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x29, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x69, 0x0a, 0x11, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x64, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x69, 0x64, 0x22, 0x6b, 0x0a,
	0x0d, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0b, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x32, 0xff, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x51, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x12,
	0x22, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x70, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x61, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x70, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x06, 0x52,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x22, 0x5a, 0x20, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x68,
	0x75, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x61, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pay_v1_pay_proto_rawDescOnce sync.Once
	file_pay_v1_pay_proto_rawDescData = file_pay_v1_pay_proto_rawDesc
)

func file_pay_v1_pay_proto_rawDescGZIP() []byte {
	file_pay_v1_pay_proto_rawDescOnce.Do(func() {
		file_pay_v1_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_v1_pay_proto_rawDescData)
	})
	return file_pay_v1_pay_proto_rawDescData
}

var file_pay_v1_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pay_v1_pay_proto_goTypes = []interface{}{
	(*CommonPayRequest)(nil),  // 0: tickethub.pay.v1.CommonPayRequest
	(*CommonPayReply)(nil),    // 1: tickethub.pay.v1.CommonPayReply
	(*TradeCheckRequest)(nil), // 2: tickethub.pay.v1.TradeCheckRequest
	(*TradeCheckReply)(nil),   // 3: tickethub.pay.v1.TradeCheckReply
	(*RefundRequest)(nil),     // 4: tickethub.pay.v1.RefundRequest
	(*RefundReply)(nil),       // 5: tickethub.pay.v1.RefundReply
}
var file_pay_v1_pay_proto_depIdxs = []int32{
	0, // 0: tickethub.pay.v1.PayService.CommonPay:input_type -> tickethub.pay.v1.CommonPayRequest
	2, // 1: tickethub.pay.v1.PayService.TradeCheck:input_type -> tickethub.pay.v1.TradeCheckRequest
	4, // 2: tickethub.pay.v1.PayService.Refund:input_type -> tickethub.pay.v1.RefundRequest
	1, // 3: tickethub.pay.v1.PayService.CommonPay:output_type -> tickethub.pay.v1.CommonPayReply
	3, // 4: tickethub.pay.v1.PayService.TradeCheck:output_type -> tickethub.pay.v1.TradeCheckReply
	5, // 5: tickethub.pay.v1.PayService.Refund:output_type -> tickethub.pay.v1.RefundReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pay_v1_pay_proto_init() }
func file_pay_v1_pay_proto_init() {
	if File_pay_v1_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_v1_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonPayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonPayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeCheckReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_v1_pay_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_v1_pay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_v1_pay_proto_goTypes,
		DependencyIndexes: file_pay_v1_pay_proto_depIdxs,
		MessageInfos:      file_pay_v1_pay_proto_msgTypes,
	}.Build()
	File_pay_v1_pay_proto = out.File
	file_pay_v1_pay_proto_rawDesc = nil
	file_pay_v1_pay_proto_goTypes = nil
	file_pay_v1_pay_proto_depIdxs = nil
}
