service:
  name: admin-service
  env: local
http:
  addr: :8007
  timeout: 5s
grpc:
  addr: :9007
  timeout: 5s
mysql:
  dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub?parseTime=true&loc=Local&charset=utf8mb4
redis:
  addr: 127.0.0.1:6379
  key_prefix: tickethub:admin
kafka:
  brokers: [127.0.0.1:9094]
  client_id: admin-service
grpc_upstreams:
  order-service: 127.0.0.1:9003
observability:
  metrics_addr: :19007
  trace_otlp: http://127.0.0.1:4318
  log_level: info
