service:
  name: base-data-service
  env: local
http:
  addr: :8005
  timeout: 5s
grpc:
  addr: :9005
  timeout: 5s
mysql:
  dsn: ${TICKETHUB_MYSQL_USER}:${TICKETHUB_MYSQL_PASSWORD}@tcp(${TICKETHUB_MYSQL_HOST})/tickethub_base?parseTime=true&loc=Local&charset=utf8mb4
redis:
  addr: 127.0.0.1:6379
  key_prefix: tickethub:base
kafka:
  brokers: [127.0.0.1:9094]
  client_id: base-data-service
observability:
  metrics_addr: :19005
  trace_otlp: http://127.0.0.1:4318
  log_level: info
